name: travel_application
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  supabase_flutter: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1

    

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf

  uses-material-design: true
  assets:
    - assets/images/home_banner_image2.png
    - assets/images/bali.png
    - assets/images/maldives.png
    - assets/images/paris.png
    - assets/images/peru.png
    - assets/images/tokyo.png
    - assets/images/user_profile.jpg
    - assets/images/on_borad_image.jpg
    - assets/images/pexels-tejas-kamble-715220277-34731910.jpg
    - assets/images/google.png
    - .env
    - assets/images/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true



  