name: travel_application
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf

  uses-material-design: true
  assets:
    - assets/images/home_banner_image2.png
    - assets/images/bali.png
    - assets/images/maldives.png
    - assets/images/paris.png
    - assets/images/peru.png
    - assets/images/tokyo.png
    - assets/images/user_profile.jpg
    - assets/images/on_borad_image.jpg
    - assets/images/pexels-tejas-kamble-715220277-34731910.jpg
    - assets/images/google.png


  